version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Grails and Java installation
          command: sudo apt-get install python-software-properties
                   sudo add-apt-repository ppa:webupd8team/java
                   sudo apt-get update
                   sudo apt-get install oracle-java7-installer