version: 2
jobs:
  build:
    docker:
      - image: altionsbs/cci-centos-altion:0.0.7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: wassup
          command: yum install sudo -y
      - run:
          name: Grails and Java installation
          command: export GRAILS_HOME=/usr/local/grails/grails-1.3.9 && export PATH=$PATH:/usr/local/grails/grails-1.3.9/bin && export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.181.x86_64 && grails test-app