version: 2
jobs:
  build:
    docker:
      - image: altionsbs/cci-centos-altion:0.0.6
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: wassup
          command: yum install sudo -y
      - run:
          name: howaya
          command: sudo su
      - run:
          name: Grails and Java installation
          command: grails help